name = "lapce-elixir-ls"
version = "0.0.1"
author = "Mayel @ Bonfire"
display-name = "Elixir LS"
description = "Language Server for Elixir"

repository = "mayel/lapce-elixir-ls"
wasm = "bin/lapce-elixir-ls.wasm"

[configuration]
language_id = "elixir"
system_lsp = false
disabled = false
release = "0.0.1"

[configuration.options.binary]
args = []